---
title: "My presentation"
author: "Rui Dong"
date: "2022-10-14"
bibliography: references.bib

header_includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage[english]{babel}
- \usepackage[utf8]{inputenc}
- \usepackage{amsmath}
- \usepackage{amsthm}
- \usepackage{mathtools}
  
output:
  pdf_document:
    number_sections: true
    toc: true
    extra_dependencies: ["amsthm", "amsmath"]
  html_notebook: default
---

```{=latex}
\theoremstyle{definition}
\newtheorem{thm}{Theorem}[section]

\theoremstyle{definition}
\newtheorem{defn}{Definition}[section]

\theoremstyle{definition}
\newtheorem{example}{Example}[section]

\newcommand{\se}{\textrm{SE}}
\newcommand{\rse}{\textrm{RSE}}
\newcommand{\tss}{\textrm{TSS}}
\newcommand{\rss}{\textrm{RSS}}
```

```{=latex}
\section{How I can contribute to the SAPPHIRE project}
```


```{=latex}
\subsection{Update the \texttt{glottodist} with different metrics other than Gower's distance}
We can implement other kinds of metrics like listed in \cite{Boriah2008SimilarityMF},
Take Eskin's distance as an example:
$$
S_k(X_k, Y_k)
=
\begin{cases}
1 &\text{if } X_k=Y_k\\
\frac{n_k^2}{n_k^2+2} &\text{otherwise}
\end{cases}
$$
```

```{=latex}
\subsection{The Hausdorff distance of two datasets}
The \textbf{Hausdorff distance} is a qunatity to measure the distance between two subsets of a metric space.
\begin{defn}[Hausdorff distance]
Let $X$ and $Y$ be two subsets of a metric space $(M, d)$.
The Hausdorff distance $d_H(X, Y)$ is given by
$$
d_H(X, Y)
=
\max\left\{\sup_{x\in X}d(x, Y), \sup_{y\in Y}d(X, y)\right\},
$$
where $d(x, Y):= \inf_{y\in Y}d(x,y)$.
\end{defn}

More than that, 
we can take the \textbf{Gromov-Hausdorff distance}, 
which measures the difference between two different datasets,
into account.
```


```{=latex}
\subsection{Topological data analysis (TDA)}
Using topological data analysis methods to analyze the \texttt{glottodata}  
\begin{itemize}
\item Linguistic data analysis: \cite{MR3767893}, \cite{MR4368966}
\item Spatial data: \cite{MR4433804}
\end{itemize}
```

```{=latex}
\subsection{Spectral graph theory methods}
Construct a graph from the \texttt{glottodata} and analyse the graph, for example, analyse the spectrum of the Laplacian operator of the graph or apply heat kernel analysis methods \cite{MR4322668} to analyse the \texttt{ glottodata}.
```

```{=latex}
\section{Some codes}
```


```{=latex}
\subsection{Load the \texttt{wals} datasets}
```

```{r}
library(glottospace)
library(dplyr)
library(TDAstats)
library(sf)
```

```{r}
# load the dataset wals
wals <- glottoget("wals")
```

```{r}
#select the data wrt Aouth America 
wals_sam <- subset(wals, continent == "South America")
wals_asia <- subset(wals, continent=="Asia")
```

```{r}
# Define a function select.features to get all features of dataset that the percentage of 
# NA values is less than the threshold a
count.na <- function (dataset, feature.name) {
  num.features <- length(st_drop_geometry(dataset))
  return(sum(is.na(dataset[[feature.name]])) / nrow(dataset))
  
}

select.features <- function(dataset, feature_names, a) {
  counts <- c()
  for (x in feature_names) {
    counts <- append(counts, count.na(wals_sam, x))
  }
  result <- t(as.matrix(counts[counts<0.5]))
  colnames(result) <- feature_names[which(counts<0.5)]
  
  return(result)
}
```

```{r}
feature_names <- colnames(wals_sam)[-c(1, 194:208)]
select.features(wals_sam, feature_names, 0.5)
```

```{r}
glottodata.wals <- function (continent_name) {
  structure <- glottocreate_structuretable(varnames = c("81A","82A", "83A", "86A", "129A"))
structure$type <- rep("factor", 5)
  wals_data <- subset(wals, continent == continent_name)
  data <- select(wals_data, 'glottocode', '81A', '82A', '83A', '86A', '129A')
  data.df <- st_drop_geometry(data)

  data.df$`81A` <- as.factor(data.df$`81A`)
  data.df$`82A` <- as.factor(data.df$`82A`)
  data.df$`83A` <- as.factor(data.df$`83A`)
  data.df$`86A` <- as.factor(data.df$`86A`)
  data.df$`129A` <- as.factor(data.df$`129A`)
  
  data.unique <- match(unique(data.df$glottocode),
                           data.df$glottocode)
  data.df.unique <- data.df[data.unique, ]
  glottodata <- glottocreate_addtable(data.df.unique, structure,
                                          name="structure")
  return(glottodata)
}

glottodata_sam <- glottodata.wals("South America")
glottodata_asia <- glottodata.wals("Asia")
```


```{=latex}
\subsection{The Hausdorff distance}
```

```{r}
overlap.dist <- function (x, y){
  sum(x != y) / length(x)
}

overlap.x.Y.dist <- function(x, Y) {
  result <- c()
  for (i in 1:nrow(Y)) {
    result <- append(result, overlap.dist(x, Y[i,]))
  }  
  return(min(result))
}

overlap.supX.Y.dist <- function(X, Y) {
  result <- c()
  for (i in 1:nrow(X)) {
    result <- append(result, overlap.x.Y.dist(X[i, ], Y))
  }
  return(max(result))
}

overlap.hausdorff.dist <- function(X, Y) {
  X <- glottoclean(X)
  structure <- X[["structure"]]
  X <- glottosimplify(X)
  X <- tibble::column_to_rownames(X, "glottocode")
  
  X <- data.frame(lapply(X, as.character),
                                stringsAsFactors = FALSE)
  X[is.na(X)] <- "unknown"
  
  Y <- glottoclean(Y)
  Y <- glottosimplify(Y)
  Y <- tibble::column_to_rownames(Y, "glottocode")
  Y <- data.frame(lapply(Y, as.character),
                                  stringsAsFactors = FALSE)
  Y[is.na(Y)] <- "unknown"
  
  
  result <- max(overlap.supX.Y.dist(X, Y), overlap.supX.Y.dist(Y,X))
  return(result)
}
```

```{=latex}
Compute the Hausdorff distance between South America and Asia:
```

```{r}
overlap.hausdorff.dist(glottodata_asia, glottodata_sam)
```


```{=latex}
\subsection{TDA}
\subsubsection{The linguistic syntactic data of South America and Asia}
```

```{r}
glottodist_sam <- glottodist(glottodata_sam)
glottodist_sam[is.na(glottodist_sam)] <- 0

glottodist_asia <- glottodist(glottodata_asia)
glottodist_asia[is.na(glottodist_asia)] <- 0
```



```{=latex}
The persistence barcode and persistence diagram of South America language syntactic structures
```


```{r}
sam.phom <- calculate_homology(glottodist_sam)

par(mfrow=c(1,2))
plot_barcode(sam.phom)
plot_persist(sam.phom)
```

```{=latex}
The persistence barcode and persistence diagram of Asia language syntactic structures
```


```{r}
asia.phom <- calculate_homology(glottodist_asia)

par(mfrow=c(1,2))
plot_barcode(asia.phom)
plot_persist(asia.phom)
```

```{=latex}
\subsubsection{The spatial data of South America and Asia}
```

```{r}
sam_coordinates <- st_coordinates(wals_sam)
asia_coordinates <- st_coordinates(wals_asia)

sam_geo_phm <- calculate_homology(sam_coordinates)
asia_geo_phm <- calculate_homology(asia_coordinates)
```

```{r}
par(mfrow=c(1,2))
plot(sam_coordinates, main="South America")
plot(asia_coordinates, main="Asia")
```


```{=latex}
The persistence barcodes of spatial data of South America and Asia:
```

```{r}
par(mfrow=c(1,2))
plot_barcode(sam_geo_phm)
plot_barcode(asia_geo_phm)

```

```{=latex}
The persistence diagrams of spatial data of South America and Asia:
```

```{r}
par(mfrow=c(1,2))
plot_persist(sam_geo_phm)
plot_persist(asia_geo_phm)
```

```{=latex}
\subsection{Futher codes}
Codes about spectral graph theory methods and heat kernel analysis methods like described in \cite{MR4322668} in the future?
```


```{=latex}
\bibliographystyle{apalike}
\bibliography{references}
```

